# Generated by Django 3.2.18 on 2023-02-28 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
